//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppPTCuenta
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarjeta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tarjeta()
        {
            this.transacciones = new HashSet<transaccione>();
        }
    
        public int id_tarjeta { get; set; }
        public string num_tarjeta { get; set; }
        public string nombre_cliente { get; set; }
        public string apellido_cliente { get; set; }
        public decimal saldo_inicial { get; set; }
        public decimal limite_credito { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transaccione> transacciones { get; set; }
    }
}
