//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppPTCuenta
{
    using System;
    using System.Collections.Generic;
    using WebAppPTCuenta.Models;

    public partial class transaccione
    {
        

        public int id_transaccion { get; set; }
        public int id_tarjeta { get; set; }
        public System.DateTime fecha_transaccion { get; set; }
        public string descripcion { get; set; }
        public decimal monto { get; set; }
        public int tipo_transaccion { get; set; }
        public string num_autorizacion { get; set; }
    
        public virtual tarjeta tarjeta { get; set; }
    }

    public class EstadoCuenta
    {
        public string NombreCliente { get; set; }
        public string NumeroTarjeta { get; set; }
        public decimal SaldoInicial { get; set; }
        public decimal SaldoActual { get; set; }
        public int NumeroAutorizacion { get; set; }
        public DateTime FechaTransaccion { get; set; }
        public decimal Limite { get; set; }
        public decimal InteresBonificable { get; set; }
        public decimal CuotaMinimaAPagar { get; set; }
        public decimal MontoTotalAPagar { get; set; }
        public decimal MontoTotalContadoConIntereses { get; set; }
        public decimal SaldoDisponible { get; set; }
        public List<transaccione> Transacciones { get; set; } // Lista de transacciones asociadas
        public decimal TotalComprasDiciembre { get; set; }
        public decimal TotalComprasEnero { get; set; }

        public static implicit operator EstadoCuenta(EstadoCuenta v)
        {
            throw new NotImplementedException();
        }
    }
}
